### ISSUE TITLE
Quarter 1 Planning

### ISSUE THREAD

**Issue by charankumarpalla** [charankumarpalla/laughing-buddha#1]

**Comment by charankumarpalla** [comment]
Story Board for Q1 as discussed are as below : 

- [ ] **[Java](https://www.quora.com/What-is-a-complete-list-of-topics-of-Core-Java-and-topics-of-Advanced-Java/answer/Suraj-Kadam-12?ch=10&share=a984d5d0&srid=vXB8)**   
   - [ ] **Basic Java**
   - [ ] **Advanced  Java**
  
- [ ]  **Python** -> **Machine Learning**

**Comment by sagar20896** [comment]
First 3 sprints (Java, as of now)

- [ ] Core Java Programming Introduction of Java

- [ ] Data types and Operators

- [ ] Control Flow statements

- [ ] OOPS and its application in Java
